# -*- coding: utf-8 -*-
"""notebook461ba37077

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebook#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/swapnilsoni/notebook461ba37077.5cbd8dae-8f5d-4673-aac9-06b8796c8238.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260921/auto/storage/goog4_request%26X-Goog-Date%3D20260921T105128Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D036f40d8118ba40a2ab08e6dc05961ad9943befa05a993447f7a5669925f632fadae4e2e375421cc770ecfa95e4938608198eb5e80dc4d70e89d4d0eb1428b788af858ae2e6bbb3144abb8012a4d1991d0978a69d579116c9bc290a5788c589ffa7d96daad759c73008c1485eb9b1c8dcc9145edb89833f72c11c4ff6c944e033e9dbd36c6f4924d55b73d112f796ae04c9bbd00584b329656827f9966ea7c9626f4d7b89c736ae0df2492b56ba859beedff9b3782f69fee3ea9bc5335b463015a7b138a3ac4bbc8f7c1fae1314629c419ef654cbfa53fc12478749be9debe21c5af43162cf04559cb1fa558894a79c08985afb0e7de13175e253daa17fb8c26
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from dataclasses import dataclass
import math
import time
import contextlib
import os
import shutil
import json
from optimum.quanto import quantize, freeze, qint8
from datasets import Dataset as HFDataset
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence

from torch.quantization import (
    get_default_qconfig,
    prepare,
    convert,
    QConfig,
    MinMaxObserver,
    HistogramObserver,
    PerChannelMinMaxObserver
)

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')



device = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_NAME="TinyLlama/TinyLlama-1.1B-Chat-v1.0"
print("MODEL_NAME = ",MODEL_NAME)
print("device = ",device)

"""# Utilities
This section contains utility functions:
- To measure the size of a directory in megabytes.
- To monitor GPU memory usage during execution.
- To define a data structure for storing generation metrics.
"""

@dataclass
class GenMetrics:
  latency_s:float
  tokens_per_sec:float
  peak_gpu_mem_mb:float

def print_row(title, size_mb, lat_s, tps, gpu_mb, ppl):
    print(
        f"{title:18s} | Size: {size_mb:8.1f} MB | Latency: {lat_s:7.3f} s | "
        f"Throughput: {tps:7.2f} tok/s | Peak VRAM: {gpu_mb:7.1f} MB | PPL: {ppl:7.2f}"
    )

def dir_size_mb(path: str) -> float:
    total = 0
    for root, _, files in os.walk(path):
        for f in files:
            total += os.path.getsize(os.path.join(root, f))
    return total / (1024**2)

def save_and_size(model, tokenizer, out_dir)-> float:
  if os.path.exists(out_dir):
    shutil.rmtree(out_dir)
  os.makedirs(out_dir, exist_ok=True)
  # name = os.path.join(out_dir, "model")
  model.save_pretrained(out_dir)
  tokenizer.save_pretrained(out_dir,safe_serialization=True)
  return dir_size_mb(out_dir)

@torch.no_grad()
def compute_perplixity(model, tokenizer, seq_len = 128):
  eval_text = "In the rapidly evolving landscape of modern technology, artificial intelligence stands out as a transformative force that is fundamentally reshaping how humanity interacts, works, and solves complex problems across global industries, because its advanced machine learning algorithms can analyze vast datasets with unprecedented speed, automate intricate workflows, and generate human-like insights, which ultimately empowers businesses to optimize their efficiency, assists doctors in diagnosing critical illnesses more accurately, and enables developers to create highly innovative software solutions that were completely unimaginable just a few short decades ago, paving the way toward a highly connected and intelligent future."
  input_tokens = tokenizer(eval_text, return_tensors="pt")
  input_ids = input_tokens['input_ids'][0]
  loss_total = 0.0
  total_token = 0
  model.eval()
  for start in range(0, len(input_ids) - seq_len, seq_len):
    chunk = input_ids[start:start + seq_len + 1]
    inp    = chunk[:-1].unsqueeze(0).to(device)
    labels = chunk[1:].unsqueeze(0).to(device)
    out = model(input_ids = inp, labels = labels)
    loss_total += float(out.loss * labels.numel())
    total_token += labels.numel()
  loss = loss_total / total_token
  return math.exp(loss)

@contextlib.contextmanager
def torch_cuda_monitor():
  if device == "cuda":
    torch.cuda.reset_peak_memory_stats()
    torch.cuda.synchronize()
    try:
      yield
    finally:
      torch_cuda_monitor.peak_mb = torch.cuda.max_memory_allocated() / (1024**2)
      torch_cuda_monitor.start_mb = torch.cuda.memory_allocated() / (1024**2)
      torch.cuda.empty_cache()
    torch.cuda.synchronize()
  else:
    try:
      yield
    finally:
      torch_cuda_monitor.peak_mb = 0.0
      torch_cuda_monitor.start_mb = 0.0

"""# Measure Text Generation Performance
This function:
- Measures the latency, throughput, and peak GPU memory usage during text generation.
- Performs a warmup run to stabilize performance.
- Uses multiple runs to calculate average metrics for better accuracy.
"""

def measure_generate(model, tokenizer, prompt, max_new_token = 64, runs = 3)->GenMetrics:
  model.eval()
  #tokenize the prompt and move to device
  tokens = tokenizer(prompt, return_tensors ="pt")
  tokens= {k:v.to(device) for k, v in tokens.items()}
  input_len = tokens['input_ids'].shape[1]
  total_latencies = []
  tps = []
  #warmup
  with torch.no_grad():
      _ = model.generate(**tokens, max_new_tokens=8, do_sample=False, use_cache=True)
  with torch_cuda_monitor():
    for _ in range(runs):
      if device == "cuda":
        torch.cuda.synchronize()

      with torch.no_grad():
        start = time.perf_counter()
        out = model.generate(**tokens, max_new_tokens=max_new_token, do_sample=False, use_cache=True)
      if device == "cuda":
        torch.cuda.synchronize()
      end = time.perf_counter()
      lat = end - start
      total_latencies.append(lat)
      gen_token = out.shape[1] - input_len
      tps.append(gen_token / lat)
      return GenMetrics(sum(total_latencies)/len(total_latencies),
                        sum(tps)/len(tps),
                        getattr(torch_cuda_monitor, "peak_mb", 0.0))

"""# Load Tokenizer
- Loads the tokenizer for the specified model.
- Ensures that padding tokens are set to make generation and perplexity calculations robust.
"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
if tokenizer.pad_token is None:
  tokenizer.pad_token = tokenizer.eos_token

"""# Baseline FP32 Model Evaluation
- Loads the baseline FP32 model.
- Measures the model's size, latency, throughput, and perplexity.
- Prints the evaluation metrics for the baseline model.
"""

fp32_model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.float32,low_cpu_mem_usage=True)
fp32_model.to(device)
baseline_size_mb = save_and_size(fp32_model, tokenizer, out_dir="tinyllama_fp32")
baseline_metrics = measure_generate(fp32_model, tokenizer, "Explain quantization in one paragraph for ML engineers")
baseline_ppl = compute_perplixity(fp32_model, tokenizer)
print_row("FP32 (baseline)", ptq_size_mb, ptq_metrics.latency_s,
          ptq_metrics.tokens_per_sec, ptq_metrics.peak_gpu_mem_mb,ptq_ppl)

ptq_model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)
quantize(ptq_model, qint8)
freeze(ptq_model)
ptq_model.to(device)

ptq_size_mb = save_and_size(ptq_model, tokenizer, out_dir="tinyllama_int8")
ptq_metrics = measure_generate(ptq_model, tokenizer, "Explain quantization in one paragraph for ML engineers")
ptq_ppl = compute_perplixity(ptq_model, tokenizer)
print_row("PTQ INT8", ptq_size_mb, ptq_metrics.latency_s,
          ptq_metrics.token_per_sec, ptq_metrics.peak_gpu_mem_mb,ptq_ppl)

summary = {
    "device": device,
    "model": MODEL_NAME,
    # "seed": SEED,
    "baseline_fp32": {
        "size_mb": baseline_size_mb,
        "latency_s": baseline_metrics.latency_s,
        "tokens_per_sec": baseline_metrics.tokens_per_sec,
        "peak_gpu_mem_mb": baseline_metrics.peak_gpu_mem_mb,
        "perplexity": baseline_ppl,
    },
    "int8_quanto": {
        "size_mb": ptq_size_mb,
        "latency_s": ptq_metrics.latency_s,
        "tokens_per_sec": ptq_metrics.tokens_per_sec,
        "peak_gpu_mem_mb": ptq_metrics.peak_gpu_mem_mb,
        "perplexity": ptq_ppl,
    },
}
with open("ptq_tinyllama_summary.json", "w") as f:
    json.dump(summary, f, indent=2)

print("\nSaved summary -> ptq_tinyllama_summary.json")

def build_calibration_texts():
    """
    Return ~15–30 short, varied sentences for calibration.
    Mixed styles: facts, questions, lists, numbers, dates, code-ish, etc.
    Each is short to keep tokenization light.
    """
    CALIB_TEXTS = [
        "Neural networks approximate functions by composing linear and nonlinear transformations.",
        "How many parameters are in a small language model with 100 million weights?",
        "Shopping list: apples, rice, coffee beans, and two bottles of water.",
        "Python snippet: for i in range(3): print(i) # demo",
        "In 2024, researchers explored post-training quantization to reduce memory while preserving accuracy.",
        "Temperature today is 18°C with light winds from the west.",
        "Please summarize the article in one concise paragraph.",
        "Quantization maps FP32 weights to lower-precision formats like INT8.",
        "Q: What is perplexity? A: A measure of how confidently a model predicts tokens.",
        "TODO: refactor the data loader and add unit tests for edge cases.",
        "Benchmark setup: batch size 1, max new tokens 64, three runs, median latency.",
        "The matrix A has eigenvalues [1.2, 0.7, 0.1] indicating contraction.",
        "Version 1.3.7 fixed a regression in the tokenizer’s handling of special tokens.",
        "A short story: The rover paused, scanned the ridge, and rolled forward.",
        "CPU vs GPU: choose based on throughput, latency, and cost targets.",
        "Top-3 tasks: clean data, train baseline, and ship a minimal dashboard.",
        "Security note: never log API keys or tokens to stdout.",
        "Quantization-aware training simulates low precision during training to reduce accuracy loss.",
        "Meeting at 10:30 on Friday to review metrics and decide next steps.",
        "Answer in bullet points: speed, memory, energy, and portability.",
        "The dataset contains 120,000 rows and 17 columns, mostly numeric features.",
        "Question: Why does dynamic quantization help Linear layers on CPU?",
        "The compiler emitted warnings about deprecated CUDA kernels.",
        "A recipe: preheat oven to 180°C, mix ingredients, bake for 25 minutes.",
        "Inference logs include time stamps, token counts, and cache-hit ratios.",
        "Note: padding tokens should not affect loss computation or attention.",
        "Checklist: reproducibility, seeding, device placement, and data order.",
        "The model failed to converge with LR=1e-1; try 3e-4 instead.",
        "On-device AI can reduce latency and preserve privacy.",
        "Final reminder: document your experiments and commit configs."
    ]
    return CALIB_TEXTS

def prepare_data(tokenizer, calib_texts, batch_size = 4,max_length=256):

    class CalibDataSet(Dataset):
        def __init__(self, texts_):
            self.texts = texts_
        def __len__(self):
            return len(self.texts)
        def __getitem__(self, ind):
            txt = self.texts[ind]
            enc = tokenizer(txt, truncation=True,
                max_length=max_length, return_tensors="pt")
            return {k: v.squeeze(0) for k, v in enc.items()}
    pad_id = tokenizer.pad_token_id
    print('pad_id=',pad_id)
    if pad_id is None:
        # Fallback to EOS if the tokenizer has no dedicated PAD
        pad_id = tokenizer.eos_token_id

    def _collate(batch):
        input_ids_list = [b["input_ids"].to(device) for b in batch]
        if "attention_mask" in batch[0]:
            attn_list = [b["attention_mask"].to(device) for b in batch]
        else:
            # Fallback: all real tokens treated as 1s
            attn_list = [torch.ones_like(b["input_ids"].to(device)) for b in batch]

        input_ids = pad_sequence(input_ids_list, batch_first=True, padding_value=pad_id)
        attention = pad_sequence(attn_list, batch_first=True, padding_value=0)
        return {"input_ids": input_ids, "attention_mask": attention}
    ds = CalibDataSet(calib_texts)
    return DataLoader(ds, batch_size=batch_size, shuffle=False, collate_fn=_collate)

texts = build_calibration_texts()
dl = prepare_data(tokenizer, texts)
print(dl)
# def __init__(self, texts_):
#             self.texts = texts_
#         def __len__(self):
#             return len(self.texts)
#         def __getitem__(self, idx):
#             enc = tokenizer(
#                 self.texts[idx],
#                 truncation=True,
#                 max_length=max_length,
#                 return_tensors="pt",
#             )
#             # squeeze to 1D tensors
#             return {k: v.squeeze(0) for k, v in enc.items()}

def run_static_ptq_optimum(fp32_model, tokenizer, dl, out_dir="tinyllama-int8-static"):
    # Setup quantization
    import torch.nn as nn
    print("\n[2] Setting up quantization...")
    qconfig = QConfig(
        activation=HistogramObserver.with_args(reduce_range=True),
        weight=MinMaxObserver.with_args(
            dtype=torch.qint8,
            qscheme=torch.per_tensor_affine  # Supported
        )
    )
    fp32_model.qconfig = qconfig

    # Prepare (insert observers)
    print("\n[3] Preparing model...")
    prepare(fp32_model, inplace=True)
     # IMPORTANT: Skip embedding layers from quantization
    def skip_embedding_quant(module):
        """Skip quantization for Embedding layers"""
        for name, submodule in module.named_modules():
            if isinstance(submodule, nn.Embedding):
                print(f"  ⊘ Skipping quantization for: {name}")
                submodule.qconfig = None

    skip_embedding_quant(fp32_model)
    print("  ✓ Embedding layers skipped")
    print("Observers inserted")
    with torch.no_grad():
        for i, batch in enumerate(dl):
            # print(batch)
            # batch = [for]
            fp32_model(**batch)
            if (i + 1) % 25 == 0:
                print(f"   {i + 1}/100")
    print(" Calibration done")

    # Convert to INT8
    print("\n[5] Converting to INT8...")
    model_int8 = convert(fp32_model, inplace=False)
    ptq_size_mb = save_and_size(model_int8, tokenizer, out_dir="tinyllama_fp32")
    ptq_metrics = measure_generate(model_int8, tokenizer, "Explain quantization in one paragraph for ML engineers")
    ptq_ppl = compute_perplixity(model_int8, tokenizer)
    print(" Conversion done")
    print_row("PTQ INT8", ptq_size_mb, ptq_metrics.latency_s,
          ptq_metrics.tokens_per_sec, ptq_metrics.peak_gpu_mem_mb,ptq_ppl)

run_static_ptq_optimum(fp32_model, tokenizer, dl)



